site_name: "Kew Bioinformatics Documentation"
site_url: https://rbg-kew-bioinformatics-utils.readthedocs.io

theme: 
  name: readthedocs
  highlightjs: true

plugins: 
  - search
  - mkdocstrings:
      handelers:
        python:
          option:docstring_style: sphinx
markdown evtentions:
  - markdown_include.include:
      base_path: .
  - admonition


nav: 
  - Services:
    - HPC : services/cropdiversityhpc.md
    - KewStorage : services/hpcstorage.md
    - SFTP : services/SFTP_service.md
  - Tutorials:
    - Key pairs: tutorials/keypair.md
    - Storage Types : tutorials/storage.md
    - SLURM Optimisation : tutorials/slurmresources.md
