site_name: "Kew Bioinformatics Documentation"
site_url: https://rbg-kew-bioinformatics-utils.readthedocs.io

theme: 
  name: readthedocs
  highlightjs: true

plugins: 
  - search
  - mkdocstrings:
      handelers:
        python:
          option:docstring_style: sphinx
markdown evtentions:
  - markdown_include.include:
      base_path: .
  - admonition


nav: 
  - Services:
    - KewStorage : Services/KewStorage.md
    - SFTP.kew.org : Services/External_SFTP_Service.md
  - Tutorials:
    - Anaconda: software/anaconda.md
#    - BASH (Linux Command Line): software/bash.md
    - GATK: software/gatk.md
    - HybPiper: software/hybpiper.md
    - Ipyrad: software/ipyrad.md
    - Python: software/python.md
    - R: software/r.md
    - Trimmomatic: software/trimmomatic.md

